### ISSUE TITLE
USERNAME sukhatri Tracking issues to track progress on GitHUB Work Flow

### ISSUE THREAD

**Issue by sukhatri** [githubteacher/developers-jun-2016-americas#243]
# Sukhatri's Workflow :tada:
- [x] create a  branch
- [x] add commits on my own branch
- [x] open a pull request
- [x] collaborate and have a a conversation
- [ ] make some more commits
- [ ] Merge our branch into master
